# enable persistence
persistence: true
volumes:
  persistence: true

affinity:
  anti_affinity: false

## start
components:
  # zookeeper
  zookeeper: true
  # bookkeeper
  bookkeeper: false
  # bookkeeper - autorecovery
  autorecovery: false
  # broker
  broker: false
  # functions
  functions: false
  # proxy
  proxy: false
  # toolset
  toolset: false
  # pulsar manager
  pulsar_manager: false

monitoring:
  # monitoring - prometheus
  prometheus: false
  # monitoring - grafana
  grafana: false
  # monitoring - node_exporter
  node_exporter: false
  # alerting - alert-manager
  alert_manager: false

zookeeper:
  replicaCount: 1
  configData:
    PULSAR_EXTRA_OPTS: >
      -XX:+UnlockDiagnosticVMOptions
      -XX:+DebugNonSafepoints
      -XX:+FlightRecorder
      -XX:FlightRecorderOptions=stackdepth=1024
    PULSAR_MEM: >
      -Xms64m -Xmx256m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dcom.sun.management.jmxremote
      -Djute.maxbuffer=10485760
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:+DisableExplicitGC
      -XX:+PerfDisableSharedMem